version: "3.9"

x-default-config: &default-service-config
  platform: linux/arm64
  networks:
    - local_network
  logging:
    options:
      max-size: 50m
  restart: 'no'

services:
  gateway:
    <<: *default-service-config
    container_name: gateway
    hostname: gateway
    build:
      context: gateway
    ports:
      - 8080:8080
    command: uvicorn gateway.app.asgi:app --host 0.0.0.0 --port 8080 --workers 1

networks:
  local_network:
