version: "3.9"

x-db-variables: &db-variables
  POSTGRES_HOST: db
  POSTGRES_PASSWORD: password12345
  POSTGRES_USER: postgres

x-kafka-variables: &kafka-variables
  KAFKA_ADDR: kafka:9092

x-default-config: &default-service-config
  platform: linux/arm64
  networks:
    - local_network
  logging:
    options:
      max-size: 50m
  restart: "no"

services:
  gateway:
    <<: *default-service-config
    container_name: gateway
    hostname: gateway
    build:
      dockerfile: gateway/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - kafka
    environment:
      <<: [*db-variables, *kafka-variables]

  taskman:
    <<: *default-service-config
    container_name: taskman
    hostname: taskman
    build:
      dockerfile: taskman/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
      - kafka
    environment:
      <<: [*db-variables, *kafka-variables]

  accounting:
    <<: *default-service-config
    container_name: accounting
    hostname: accounting
    build:
      dockerfile: accounting/Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - db
      - kafka
    environment:
      <<: [*db-variables, *kafka-variables]

  analytics:
    <<: *default-service-config
    container_name: analytics
    hostname: analytics
    build:
      dockerfile: analytics/Dockerfile
    ports:
      - 8083:8080
    depends_on:
      - db
      - kafka
    environment:
      <<: [*db-variables, *kafka-variables]

  db:
    <<: *default-service-config
    container_name: db
    hostname: db
    build:
      context: db
    ports:
      - 5432:5432
    environment:
      <<: *db-variables

  ################
  # Kafka services

  kafka-ui:
    <<: *default-service-config
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_LOGGING_LEVEL_ROOT=INFO

  zookeeper:
    <<: *default-service-config
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    <<: *default-service-config
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - 29092:29092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./kafka_data/1:/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_offsets_topic_replication_factor: 1
      # KAFKA_CREATE_TOPICS: "user-streaming:1:1,task-streaming:1:1,task-lifecycle:1:1,accounting:1:1"

networks:
  local_network:
